#!/bin/bash
fun_swap() {
    clear
		echo -e "\E[44;1;37m            MANAGE MEMORY VIRTUAL             \E[0m"
        echo ""
		echo -e "\033[1;31mSwap is a swap area used to increase the amount of RAM memory \nsystem (RECOMMENDED FOR MACHINES WITH LITTLE RAM).\033[0m"
        echo -e "\033[1;31mBefore activating, know how much storage your machine has, \nalways leave plenty of storage to avoid crashes.\033[0m"
        echo ""
		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mACTIVATE SWAP / CHANGE SWAP VALUE \033[0m"
		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mDISABLE SWAP\033[0m"
		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mTO GO BACK\033[0m"
		echo ""
		echo -ne "\033[1;32mWHAT DO YOU WANT TO DO \033[1;33m?\033[1;37m "
		read resposta
		if [[ "$resposta" = '1' ]]; then
            clear
			echo -e "\E[44;1;37m            MEMORY VIRTUAL              \E[0m"
			echo ""
			echo -ne "\033[1;32mHOW MANY GIGAS DO YOU WANT TO USE \033[1;33m?\033[1;37m: "
			read gigas
            [[ -z "$gigas" ]] && {
					echo ""
					echo -e "\033[1;31mInvalid gigas!"
					sleep 2
					clear
					menu
				}
            echo ""
			echo -e "\033[1;32mSTARTING MEMORY VIRTUAL \033[1;31m$gigas GB\033[1;33m"
			echo ""
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            fallocate -l ${gigas}G /bin/ram.img > /dev/null 2>&1
            chmod 600 /bin/ram.img > /dev/null 2>&1
            mkswap /bin/ram.img > /dev/null 2>&1
            swapon /bin/ram.img > /dev/null 2>&1
            echo 50  > /proc/sys/vm/swappiness
            echo '/bin/ram.img none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32mVIRTUAL MEMORY ACTIVATED SUCCESSFULLY\033[1;33m"
            sleep 2
			fun_swap
        elif [[ "$resposta" = '2' ]]; then
            clear
			echo -e "\E[44;1;37m            DISABLING VIRTUAL MEMORY              \E[0m"
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32mVIRTUAL MEMORY DISABLED SUCCESSFULLY!\033[1;33m"
			sleep 2
			fun_swap
        elif [[ "$resposta" = '0' ]]; then
			echo ""
			echo -e "\033[1;31mReturning...\033[0m"
			sleep 1
			menu
		else
			echo ""
			echo -e "\033[1;31mInvalid option!\033[0m"
			sleep 1
			fun_swap
		fi 
}
fun_swap